### ISSUE TITLE
deutschland workflow is failing

### ISSUE THREAD

**Issue by t-huyeng** [bundesAPI/nina-api#24]
@wirthual  do you have a chance to look at this?

looks like it is still an issue with the versions:
`Only one sdist may be uploaded per release.`

See: https://github.com/bundesAPI/nina-api/actions/runs/4324499161

**Comment by wirthual** [comment]
Yes. Let me have a look. Thanks for the reminder.

**Comment by wirthual** [comment]
Actually thats the right way to do it, since you can not upload a package with the same version twice.

`Skipping de_nina-1.0.2-py3-none-any.whl because it appears to already  exist `

A nice thing would be to pull the version from the git tag at some point. But for now, let me bump the version manually.

**Comment by t-huyeng** [comment]
True, I just remembered we already talked about this here : https://github.com/wirthual/deutschland-generator-action/issues/3

**Comment by wirthual** [comment]
Ah I remember. 

Could you add a note in the readme why someone would need to use 1.0.2 instead of 1.1.0?
